### ISSUE TITLE
Continuation indent is doubled when indentation and function signature are enabled

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#5366]
x-posting from https://github.com/pinterest/ktlint/issues/1661 because ktlint itself isn't the issue

## Expected Behavior
I expect a single indent to be used for continuation indents.

[The Kotlin style guide migration suggests that:](https://kotlinlang.org/docs/code-style-migration-guide.html#differences-between-kotlin-coding-conventions-and-intellij-idea-default-code-style)

> In Kotlin coding conventions, it's recommended to use a single indent in cases where the long continuation indent has been forced before.

## Observed Behavior
A double indent is being used.

## Steps to Reproduce

[repro project](https://github.com/detekt/detekt/files/9678702/continuation_indent.zip)

The issue can be seen using the command `./gradlew detektMetadataMain`. In between each of these cases, I am running `git reset --hard` in order to reset the file to original formatting. The rules can be configured in the `detekt.yml` file.

1. `Indentation` and `FunctionSignature` enabled - two function bodies are moved inline with the signature and indentation is doubled for continuations
2. `Indentation` enabled and `FunctionSignature` disabled - no changes
3. `Indentation` disabled and `FunctionSignature` enabled - two function bodies are moved inline with the signature

Contrast this with running `ktlint "repro/src/**/*.kt" --experimental -F` which only auto formats the `FunctionSignature` violation.

## Your Environment
Detekt 1.22.0-RC1
Gradle 7.5.1
Kotlin 1.7.10

**Comment by 3flex** [comment]
Possibly related to #5259, though I haven't confirmed.

**Comment by sanggggg** [comment]
Oh... I found the reason why. This bug is already resolved in #5312 

When `FunctionSignature` rule is enabled on `1.22.0-RC1`, `DefaultEditorConfigProperties.indentSizeProperty` is set to `FunctionSignature`'s indentSize config. (which is `4` in reproducing project)
https://github.com/detekt/detekt/blob/283da9ee7921f3d1c4dfda2f10d8d900a38d02b6/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/FunctionSignature.kt#L41

`DefaultEditorConfigProperties.indentSizeProperty` change global configuration `KtLint.EDITOR_CONFIG_PROPERTIES_USER_DATA_KEY`, so it affects the later formatting of the `Indent` rule. (indenting with `4`, not `2`)

https://github.com/detekt/detekt/blob/283da9ee7921f3d1c4dfda2f10d8d900a38d02b6/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingRule.kt#L69-L78

And thanks to #5312 this bug is resolved.
I think we can close this issue @3flex (this issue is not related to #5259)

**Comment by eygraber** [comment]
I'm still seeing this behavior in RC2 (not sure if #5312 is included in that build or not)

**Comment by 3flex** [comment]
RC2 and the final 1.22.0 release used ktlint 0.47.1, so if you still saw the issue in RC2 it's likely not fixed in the final release. It would be great if you can reconfirm on the snapshot version of detekt (which uses ktlint 0.48.1).

**Comment by eygraber** [comment]
Looks like the original issue is resolved.

Not sure if I should file a separate issue for this, but with the latest snapshot:

```
      val failure = try {
        client.newCall(request).execute().closeSilently()
        null
      }
      catch(t: Throwable) {
        t
      }
```

gets corrected to:

```
      val failure = try {
        client.newCall(request).execute().closeSilently()
        null
      }
        catch(t: Throwable) {
          t
        }
```

and 

```
typealias MutableSurveyInterviewResponse =
  HashMap<SurveyInterviewResponseId, SurveyInterviewResponseValue?>
```

gets corrected to:

```
typealias MutableSurveyInterviewResponse =
HashMap<SurveyInterviewResponseId, SurveyInterviewResponseValue?>
```

**Comment by 3flex** [comment]
I think a separate defect if that's ok - and can you please confirm in that issue whether ktlint does this when run directly (and if it does, it should be raised with ktlint project instead of detekt), thanks!

**Comment by eygraber** [comment]
https://github.com/detekt/detekt/issues/5720
