### ISSUE TITLE
Gradle 9.1 (rc1) deprecation of ReportingExtension.file

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#8452]
## Expected Behavior
Compatible API is used from the moment it's available.

## Observed Behavior
```
The ReportingExtension.file(String) method has been deprecated. This is scheduled to be removed in Gradle 10. Please use the getBaseDirectory().file(String) or getBaseDirectory().dir(String) method instead. Consult the upgrading guide for further information: https://docs.gradle.org/9.1.0-rc-1/userguide/upgrading_version_9.html#reporting_extension_file
	at org.gradle.api.reporting.ReportingExtension.file(ReportingExtension.java:98)
	at io.gitlab.arturbosch.detekt.DetektPlugin.apply(DetektPlugin.kt:28)
	at io.gitlab.arturbosch.detekt.DetektPlugin.apply(DetektPlugin.kt:18)
```

## Steps to Reproduce
Apply plugin on a project using Gradle 9.1.

## Context
I have Gradle warnings as errors turned on in all my repos to detect these kinds of problems.

## Your Environment
* Version of detekt used: 1.23.8
* Version of Gradle used (if applicable): 9.1-rc-1
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: any
* Link to your project (if it's a public repository):
Pretty much all repos: https://github.com/pulls?q=is%3Apr+archived%3Afalse+org%3ATWiStErRob+%22Update+dependency+gradle+from+9.0.0+to+9.1.0-rc-1%22 (see first commit's CI in most of these PRs)

**Comment by 3flex** [comment]
Can you try a snapshot? This should already be fixed:

In 1.23.8:
https://github.com/detekt/detekt/blob/046263730eb5368cb344489ac36543294e8e87bd/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt#L28

In last commit on `main`:
https://github.com/detekt/detekt/blob/1c7f84f8c90af56d133ba250ee44f166d3e528ba/detekt-gradle-plugin/src/main/kotlin/dev/detekt/gradle/plugin/DetektBasePlugin.kt#L46-L48

**Comment by schalkms** [comment]
@TWiStErRob please comment again if 1.23.8 does not fix the issue.

**Comment by TWiStErRob** [comment]
_Sorry for the late reply, I was on a long holiday._

Fix looks reasonable by read.
Couldn't try it, because there's no "named" version available in stable maven. [Snapshot](https://detekt.dev/docs/introduction/snapshots/) didn't work for some reason.

Would it be ok to get the fix to the 1.x line? (in case there'll be a 1.23.9) Happy to open a PR for it.
```diff
-extension.reportsDir = project.extensions.getByType(ReportingExtension::class.java).file("detekt")
+extension.reportsDir = project.extensions.getByType(ReportingExtension::class.java).baseDirectory.dir("detekt").get()
```
(ReportingExtension.baseDirectory is since Gradle 4.4)

**Comment by 3flex** [comment]
> in case there'll be a 1.23.9

There are no further 1.23.x releases planned.

Snapshot builds should be up soon, #8566 was just merged to fix that but the publishing didn't work when merged to `main`. This should be addressed soon though, follow https://github.com/detekt/detekt/issues/8484
